version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgis/postgis:15-3.3'
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5432:5432'
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 3s
      retries: 10

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - './redis-data:/var/lib/redis/data:rw'
    healthcheck:
      test: [ "CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 3s
      retries: 10

  bayanat:
    container_name: bayanat
    image: bayanat
    build:
      context: .
      dockerfile: ./flask/Dockerfile
      args:
        - ROLE=flask
        - ENV_FILE=${ENV_FILE:-.env}
    volumes:
      - '${MEDIA_PATH:-./enferno/media}:/app/enferno/media:rw'
      - './enferno/imports:/app/enferno/imports:rw'
      - './logs:/app/logs:rw'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    ports:
      - '127.0.0.1:5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ || exit 1"]
      interval: 3s
      retries: 10

volumes:
  redis_data:
  postgres_data:
